# Generated by Django 4.1.3 on 2023-02-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classtime",
            options={
                "ordering": ["time_start"],
                "verbose_name": "Время занятия",
                "verbose_name_plural": "Время занятий",
            },
        ),
    ]
