# Generated by Django 4.1.3 on 2023-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_alter_classtime_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="name_kk",
            field=models.CharField(max_length=30, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="discount",
            name="name_ru",
            field=models.CharField(max_length=30, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="packet",
            name="name_kk",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="packet",
            name="name_ru",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="name_kk",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="name_ru",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Название"
            ),
        ),
    ]
