version: "3.9"

services:
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
      - "80:80" # port exposed to outside world.
      # - "443:443" # <--- add this line
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      # - ./persistentdata/certbot/conf:/etc/letsencrypt # <--here
      # - ./persistentdata/certbot/www:/var/www/certbot
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/uploads:/var/www/uploads
  django-backend:
    restart: always
    build:
      context: .
    image: djangobackend
    volumes:
      - ./persistentdata/static:/var/www/static # <--here
      - ./persistentdata/uploads:/var/www/uploads # <--here
  postgresql-db:
    restart: always
    image: postgres
    volumes:
            - ./persistentdata/db:/var/lib/postgresql/data
    env_file:
      - ./postgresql-db/.pg-env # why - see the next step
  # certbot:
    # image: certbot/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # volumes:
      # - ./persistentdata/certbot/conf:/etc/letsencrypt # <--here
      # - ./persistentdata/certbot/www:/var/www/certbot