# Generated by Django 4.1.3 on 2023-01-29 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.TextField(verbose_name="Задание")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Загрузить домашнее задание",
                        null=True,
                        upload_to="homework/",
                        verbose_name="Вложение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Домашнее задание",
                "verbose_name_plural": "Домашние задания",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата проведения")),
                (
                    "topic",
                    models.TextField(blank=True, null=True, verbose_name="Тема урока"),
                ),
                (
                    "is_conducted",
                    models.BooleanField(default=False, verbose_name="Проведен"),
                ),
                (
                    "auditorium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.auditorium",
                    ),
                ),
                (
                    "class_time",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.classtime",
                        verbose_name="Номер урока",
                    ),
                ),
                (
                    "grouping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.grouping",
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="lessons.homework",
                    ),
                ),
                (
                    "students_visited",
                    models.ManyToManyField(
                        blank=True,
                        related_name="lessons_visited",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Присутствовавшие студенты",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="accounts.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Занятия",
            },
        ),
    ]
