# Generated by Django 4.1.3 on 2023-02-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="iin",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="ИИН"
            ),
        ),
    ]
