# Generated by Django 4.1.3 on 2023-02-05 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0002_studentcontract"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundsDebiting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата списания")),
                ("period", models.DateField(verbose_name="Списание за месяц")),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="Сумма к списанию"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_fund_debitings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Списание средств",
                "verbose_name_plural": "Списания средств",
            },
        ),
    ]
