# Generated by Django 4.1.3 on 2023-02-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_fundsdebiting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundsdebiting",
            options={
                "ordering": ["-period"],
                "verbose_name": "Списание средств",
                "verbose_name_plural": "Списания средств",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-date"],
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
        migrations.AlterField(
            model_name="studentcontract",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания обучения"
            ),
        ),
    ]
