# Generated by Django 4.1.3 on 2023-02-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_fundsdebiting_options_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(null=True, verbose_name="Дата платежа"),
        ),
    ]
