# Generated by Django 4.1.3 on 2023-02-11 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0005_alter_payment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала больничного"),
                ),
                (
                    "end_date",
                    models.DateField(verbose_name="Дата окончания больничного"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Загрузить больничный лист",
                        null=True,
                        upload_to="medical_certificat/",
                        verbose_name="Вложение",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_medical_certificate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Больничный лист",
                "verbose_name_plural": "Больничные листы",
            },
        ),
    ]
