# Generated by Django 4.1.3 on 2023-02-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="parents_inn",
            field=models.CharField(
                blank=True,
                help_text="Вводить только цифры",
                max_length=12,
                null=True,
                verbose_name="ИНН родителя",
            ),
        ),
    ]
