# Generated by Django 4.1.3 on 2023-02-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_application_parents_inn"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="contract_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата контракта"
            ),
        ),
    ]
