# Generated by Django 4.1.3 on 2023-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_application_contract_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="name_kk",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="name_ru",
            field=models.CharField(
                max_length=30, null=True, unique=True, verbose_name="Название"
            ),
        ),
    ]
