name: "Django deploy workflow"

on:
  push:
    branches:
      - master

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'any_host'
      - name: clone repo and create environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd projects
            rm -r test_branch
            git clone https://github.com/Chingiz-Almukhan/test_branch.git
            cd test_branch
            docker-compose down --remove-orphans
            chmod +x entrypoint.sh
            sudo docker-compose -f docker-compose.yml up --build -d
            docker ps
            exit
